# NumPy

This notebook is based on the SciPy NumPy tutorial

```{note}    
The traditional way to import numpy is to rename it np.  This saves on typing and makes your code a little more compact.
```

In [1]:
import numpy as np

NumPy provides a multidimensional array class as well as a _large_ number of functions that operate on arrays.

NumPy arrays allow you to write fast (optimized) code that works on arrays of data.  To do this, there are some restrictions on arrays:

* all elements are of the same data type (e.g. float)
* the size of the array is fixed in memory, and specified when you create the array (e.g., you cannot grow the array like you do with lists)

The nice part is that arithmetic operations work on entire arrays&mdash;this means that you can avoid writing loops in python (which tend to be slow).  Instead the "looping" is done in the underlying compiled code

## Array Creation and Properties

There are a lot of ways to create arrays.  Let's look at a few

Here we create an array using `arange` and then change its shape to be 3 rows and 5 columns.  Note the _row-major ordering_&mdash;you'll see that the rows are together in the inner `[]` (more on this in a bit)

In [2]:
a = np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = np.arange(15).reshape(3,5)

print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


an array is an object of the `ndarray` class, and it has methods that know how to work on the array data.  Here, `.reshape()` is one of the many methods.

A NumPy array has a lot of meta-data associated with it describing its shape, datatype, etc.

In [5]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(3, 5)
15
int64
8
<class 'numpy.ndarray'>


In [6]:
#help(a)

we can also create an array from a list

In [7]:
b = np.array( [1.0, 2.0, 3.0, 4.0] )
print(b)
print(b.dtype)
print(type(b))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


we can create a multi-dimensional array of a specified size initialized all to 0 easily, using the `zeros()` function.

In [8]:
b = np.zeros((10,8))
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

There is also an analogous `ones()` and `empty()` array routine.  Note that here we can explicitly set the datatype for the array in this function if we wish. 

Unlike lists in python, all of the elements of a numpy array are of the same datatype

`linspace` creates an array with evenly space numbers.  The `endpoint` optional argument specifies whether the upper range is in the array or not

In [9]:
d = np.linspace(0, 1, 10, endpoint=False)
d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

```{admonition} Exercise
Analogous to `linspace()`, there is a `logspace()` function that creates an array with elements equally spaced in log.  Use `help(np.logspace)` to see the arguments, and create an array with 10 elements from $10^{-6}$ to $10^3$.
```

## Array Operations

most operations (`+`, `-`, `*`, `/`) will work on an entire array at once, element-by-element.

Note that that the multiplication operator is not a matrix multiply (there is a new operator in python 3.5+, `@`, to do matrix multiplicaiton.

Let's create a simply array to start with

In [10]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Multiplication by a scalar multiplies every element

In [11]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

adding two arrays adds element-by-element

In [12]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

multiplying two arrays multiplies element-by-element

In [13]:
a*a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

```{admonition} Exercise
What do you think `1./a` will do?  Try it and see
```

We can think of our 2-d array as a 3 x 4 matrix (3 rows, 4 columns).  We can take the transpose to geta 4 x 3 matrix, and then we can do a matrix multiplication

We can do some basic linear algebra operations on arrays.  The operator `@` is a matrix multiplication / dot-product operator

In [14]:
b = a.transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [15]:
a @ b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

We can sum the elements of an array:

In [16]:
a.sum()

np.int64(66)

```{admonition} Exercise
`sum()` takes an optional argument, `axis=N`, where `N` is the axis to sum over.  Sum the elements of `a` across rows to create an array with just the sum along each column of `a`.
```

We can also easily get the extrema

In [17]:
print(a.min(), a.max())

0 11


## universal functions

universal functions work element-by-element.  Let's create a new array scaled by `pi / 12`

In [18]:
b = a*np.pi/12.0
b

array([[0.        , 0.26179939, 0.52359878, 0.78539816],
       [1.04719755, 1.30899694, 1.57079633, 1.83259571],
       [2.0943951 , 2.35619449, 2.61799388, 2.87979327]])

In [19]:
c = np.cos(b)
c

array([[ 1.00000000e+00,  9.65925826e-01,  8.66025404e-01,
         7.07106781e-01],
       [ 5.00000000e-01,  2.58819045e-01,  6.12323400e-17,
        -2.58819045e-01],
       [-5.00000000e-01, -7.07106781e-01, -8.66025404e-01,
        -9.65925826e-01]])

In [20]:
d = b + c 

In [21]:
d

array([[1.        , 1.22772521, 1.38962418, 1.49250494],
       [1.54719755, 1.56781598, 1.57079633, 1.57377667],
       [1.5943951 , 1.64908771, 1.75196847, 1.91386744]])

```{admonition} Exercise
We will often want to write our own function that operates on an array and returns a new array.  We can do this just like we did with functions previously&mdash;the key is to use the methods from the `np` module to do any operations, since they work on, and return, arrays.

Write a simple function that returns $\sin(2\pi x)$ for an input array `x`.  Then test it 
by passing in an array `x` that you create via `linspace()`
```

## Slicing

slicing works very similarly to how we saw with strings.  Consider the following array:

In [22]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Now look at accessing a single element vs. a range (using slicing)

Giving a single (0-based) index just references a single value

In [23]:
a[2]

np.int64(2)

When we do a range, like `a[2:5]`, then we get the elements starting at index 2 and up to, *but not including* index 5.

That is, slicing uses the interval: [begin, end)

In [24]:
a[2:5]

array([2, 3, 4])

The `:` can be used to specify all of the elements in that dimension

In [25]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Multidimensional Arrays

Multidimensional arrays are stored in a contiguous space in memory -- this means that the columns / rows need to be unraveled (flattened) so that it can be thought of as a single one-dimensional array.  Different programming languages do this via different conventions:

![](row_column_major.png)

Storage order:

* Python/C use *row-major* storage: rows are stored one after the other
* Fortran/matlab use *column-major* storage: columns are stored one after another

The ordering matters when 

* passing arrays between languages (we'll talk about this later this semester)
* looping over arrays -- you want to access elements that are next to one-another in memory
  * e.g, in Fortran:
  ```
  double precision :: A(M,N)
  do j = 1, N
     do i = 1, M
        A(i,j) = …
     enddo
  enddo
  ```
  
  * in C
  ```
  double A[M][N];
  for (i = 0; i < M; i++) {
     for (j = 0; j < N; j++) {
        A[i][j] = …
     }
  }  
  ```
  

In python, using NumPy, we'll try to avoid explicit loops over elements as much as possible

Let's look at multidimensional arrays:

In [26]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Notice that the output of `a` shows the row-major storage.  The rows are grouped together in the inner `[...]`

Giving a single index (0-based) for each dimension just references a single value in the array

In [27]:
a[1,1]

np.int64(6)

Doing slices will access a range of elements.  Think of the start and stop in the slice as referencing the left-edge of the slots in the array.

In [28]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

Access a specific column

In [29]:
a[:,1]

array([ 1,  6, 11])

Sometimes we want a one-dimensional view into the array -- here we see the memory layout (row-major) more explicitly

In [30]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

we can also iterate -- this is done over the first axis (rows)

In [31]:
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


or element by element

In [32]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


Generally speaking, we want to avoid looping over the elements of an array in python&mdash;this is slow.  Instead we want to write and use functions that operate on the entire array at once.

````{admonition} Exercise
Consider the array defined as:

```

 q = np.array([[1, 2, 3, 2, 1],
               [2, 4, 4, 4, 2],
               [3, 4, 4, 4, 3],
               [2, 4, 4, 4, 2],
               [1, 2, 3, 2, 1]])
 
```

  * using slice notation, create an array that consists of only the `4`'s in `q` (this will be called a _view_, as we'll see shortly)
  * zero out all of the elements in your view
  * how does `q` change?
```